### ISSUE TITLE
Suggest updating the BCI2000RemoteNET.dll in this repository

### ISSUE THREAD

**Issue by s-n-1-0** [neurotechcenter/UnityBCI2000#4]
Hi,

I have finished a tutorial on UnityBCI2000.
The DLL included in this repository is outdated and the GET command is not working.

https://github.com/neurotechcenter/BCI2000RemoteNET/commit/50e5bf9dc6bfd92b4fd5ed5f2ad93a0cd8a8d135

Is it possible to replace it with a DLL that reflects the fix commit?
I think it will eliminate the confusion for a beginner like me.

**Comment by s-n-1-0** [comment]
@Personator01

**Comment by Personator01** [comment]
Newest version of BCI2000RemoteNET added to repository, [@1be473f](https://github.com/neurotechcenter/UnityBCI2000/commit/1be473fbae3bd04c222e49aaca734134ba0b193a)

**Comment by s-n-1-0** [comment]
Thank you!
